import IconButton       from './IconButton.js';
import ImgGoogle        from './img/google.png';
import ImgGmail         from './img/Gmail.png';
import ImgGmap          from './img/Gmap.png';
import ImgYoutube       from './img/youtube.png';
import ImgTwitter       from './img/twitter.png';
import ImgInsta         from './img/instagram.png';
import ImgPhoto         from './img/Gphoto.png';
import ImgAmazon        from './img/amazon.png';
import ImgDrive         from './img/Gdrive.png';
import ImgDeepL         from './img/deepl.png';
import ImgGtranslate    from './img/Gtranslate.png';
import ImgGkeep         from './img/Gkeep.png';
import ImgGakujo        from './img/gakujo.png';
import ImgShizudai      from './img/shizu.png';
import ImgOpac          from './img/opac.png';
import ImgEtyping       from './img/etyping.png';
import ImgMytyping      from './img/mytyping.png';
import ImgSushida       from './img/sushida.png';
// export const ImgYweather = './img/Yweather.png';
// export const ImgYtrans = './img/Ytrans.png';
// export const ImgEntetsu = './img/entetsu.png';
// export const ImgGeogebra = './img/geogebra.png';
// export const ImgAtcoder = './img/atcoder.png';
// export const ImgAtcoderProblems = './img/atcoderProblems.png';
// export const ImgAlgo = './img/algo.png';
// export const ImgOnedrive = './img/onedrive.png';
// export const ImgTeams = './img/teams.png';
// export const ImgGithub = './img/github.png';