export {default as IconButton      } from './IconButton.js';
export {default as ImgGoogle       } from './img/google.png';
export {default as ImgGmail        } from './img/Gmail.png';
export {default as ImgGmap         } from './img/Gmap.png';
export {default as ImgYoutube      } from './img/youtube.png';
export {default as ImgTwitter      } from './img/twitter.png';
export {default as ImgInsta        } from './img/instagram.png';
export {default as ImgPhoto        } from './img/Gphoto.png';
export {default as ImgAmazon       } from './img/amazon.png';
export {default as ImgDrive        } from './img/Gdrive.png';
export {default as ImgDeepL        } from './img/deepl.png';
export {default as ImgGtranslate   } from './img/Gtranslate.png';
export {default as ImgGkeep        } from './img/Gkeep.png';
export {default as ImgGakujo       } from './img/gakujo.png';
export {default as ImgShizudai     } from './img/shizu.png';
export {default as ImgOpac         } from './img/opac.png';
export {default as ImgEtyping      } from './img/etyping.png';
export {default as ImgMytyping     } from './img/mytyping.png';
export {default as ImgSushida      } from './img/sushida.png';
// export const ImgYweather = './img/Yweather.png';
// export const ImgYtrans = './img/Ytrans.png';
// export const ImgEntetsu = './img/entetsu.png';
// export const ImgGeogebra = './img/geogebra.png';
// export const ImgAtcoder = './img/atcoder.png';
// export const ImgAtcoderProblems = './img/atcoderProblems.png';
// export const ImgAlgo = './img/algo.png';
// export const ImgOnedrive = './img/onedrive.png';
// export const ImgTeams = './img/teams.png';
// export const ImgGithub = './img/github.png';